[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "runpod-shell"
version = "0.3.0"
description = "A Python command-line interface to manage RunPod instances"
readme = "README.md"
license = "Apache-2.0"
license-files = ["LICENSE"]
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
dependencies = [
    "runpod",
]

[project.scripts]
runpod-shell = "runpod_shell.cli:main"

[tool.setuptools.packages.find]
where = ["src"]
